# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perles < Formula
  desc "Terminal-based kanban board for beads issue tracking"
  homepage "https://github.com/zjrosen/perles"
  version "0.8.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.8/perles_0.8.8_darwin_amd64.tar.gz"
      sha256 "d7bd646d834f26f35cc0b8f8893019513e2a3b3f7719c9a754249196db8d1dee"

      define_method(:install) do
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.8/perles_0.8.8_darwin_arm64.tar.gz"
      sha256 "49d0f09de29655ed6fe2a1a2afbd4c6f8f61faa31da84b0ba95a96e6e7512e36"

      define_method(:install) do
        bin.install "perles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.8/perles_0.8.8_linux_amd64.tar.gz"
      sha256 "22b0019b3e0bd2c7624b794b78fb4840ea3443c825ce66b1014821c423464b12"
      define_method(:install) do
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.8/perles_0.8.8_linux_arm64.tar.gz"
      sha256 "67f5452deb67f0a2708b758491461791a49f5144834d3e5a4013c5a5094d361e"
      define_method(:install) do
        bin.install "perles"
      end
    end
  end

  test do
    system "#{bin}/perles", "--version"
  end
end
