# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perles < Formula
  desc "Terminal-based kanban board for beads issue tracking"
  homepage "https://github.com/zjrosen/perles"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.2/perles_0.8.2_darwin_amd64.tar.gz"
      sha256 "27d640be25aff32d587f352745881b29e4e71d1bce49e4ec6649ee3cadb4704c"

      define_method(:install) do
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.2/perles_0.8.2_darwin_arm64.tar.gz"
      sha256 "dfaaf12acd856b5bb606a40cfb935277d60f663499b3a4925f0fb7ecfc6c714c"

      define_method(:install) do
        bin.install "perles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.2/perles_0.8.2_linux_amd64.tar.gz"
      sha256 "f79a8a3cbc5c06eba674dce991ea7bd35620601f08e64d331dcdc8270aac680f"
      define_method(:install) do
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.8.2/perles_0.8.2_linux_arm64.tar.gz"
      sha256 "4844e02d5c6df1db6b21d02175a8dd4ff9450c5953bf330a677fad54812bd832"
      define_method(:install) do
        bin.install "perles"
      end
    end
  end

  test do
    system "#{bin}/perles", "--version"
  end
end
