# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perles < Formula
  desc "Terminal-based kanban board for beads issue tracking"
  homepage "https://github.com/zjrosen/perles"
  version "0.7.87"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zjrosen/perles/releases/download/v0.7.87/perles_0.7.87_darwin_amd64.tar.gz"
      sha256 "3a0262b5a80d569429cc60779d4c78399677501e20adbb7c1cd8a0da91b2aa27"

      def install
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zjrosen/perles/releases/download/v0.7.87/perles_0.7.87_darwin_arm64.tar.gz"
      sha256 "ead7a56e97f4bd6a4b72e8702a5f1e61ac6088880ca2deed16d7562149eb2d75"

      def install
        bin.install "perles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.7.87/perles_0.7.87_linux_amd64.tar.gz"
      sha256 "ada7b133bd79349a5cc937585c254ae492c2ba316d6824a5d74f52ab7d7a1f32"
      def install
        bin.install "perles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zjrosen/perles/releases/download/v0.7.87/perles_0.7.87_linux_arm64.tar.gz"
      sha256 "e12a36b2640d92853626d2bd1b5175bbead652b1fa583e706e51436cf36989a8"
      def install
        bin.install "perles"
      end
    end
  end

  test do
    system "#{bin}/perles", "--version"
  end
end
